apiVersion: apps/v1
kind: Deployment
metadata:
  name: secured-poc-app
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: secured-poc-app
  template:
    metadata:
      labels:
        app: secured-poc-app
    spec:
      containers:
      - name: app-container
        # ⚡ Configured to pull your app from your private enterprise registry
        image: vamdevgoldregistry.azurecr.io/poc-app:latest
        ports:
        - containerPort: 8080
